# Generated by Django 4.2.2 on 2023-08-21 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequency',
            name='medics_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medics_id', to='medication.medication'),
        ),
    ]
