# Generated by Django 4.2.2 on 2023-09-07 07:58

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0002_alter_frequency_medics_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docappointment',
            name='doctor_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NG', unique=True),
        ),
    ]
